using System.Globalization;
using System.Text.RegularExpressions;

namespace Jump_Bruteforcer
{
    public class Parser
    {
        public static Map Parse(string Text) => Parse(".jmap", Text);

        public static Map Parse(string Extension, string Text)
        {
            Extension = Extension.ToLower();
            List<Object> objects = new List<Object>();
            if (Extension == ".cmap" || Extension == ".jmap")
            {
                int datalinenum = 5;
                string[] args = Text.Split('\n')[datalinenum - 1].Trim().Split(' ');

                for (int i = 0; i < args.Length; i += 3)
                {
                    (int x, int y, int objectid) = (int.Parse(args[i]), int.Parse(args[i + 1]), int.Parse(args[i + 2]));
                    ObjectType o = Enum.IsDefined(typeof(ObjectType), objectid) ? (ObjectType)objectid : ObjectType.Unknown;
                    objects.Add(new(x, y, o, i / 3));
                }
            }
            else //Extension == ".txt"
            {
                const int MinParams = 10;
                const NumberStyles Style = NumberStyles.Float;

                static double ParseDouble(string s) => double.Parse(s, Style, CultureInfo.InvariantCulture);

                string[] Lines = Text.Split('\n');

                for (int i = 0; i < Lines.Length; i++)
                {
                    if (Lines[i].Trim() == string.Empty)
                    {
                        continue;
                    }
                    string[] Parameters = Lines[i].Split(',');
                    if (Parameters.Length < MinParams)
                    {
                        throw new Exception($"Expected {MinParams} parameters, found {Parameters.Length} (Line {i + 1})");
                    }
 
                    ObjectType o = ObjectNames.GetValueOrDefault(Parameters[0].ToLower());
                    int x = (int)Math.Round(ParseDouble(Parameters[1]));
                    int y = (int)Math.Round(ParseDouble(Parameters[2]));

                    objects.Add(new(x, y, o, i));
                }
            }
            return new Map(objects);

        }

        static readonly Dictionary<string, ObjectType> ObjectNames = new()
        {
            {"block", ObjectType.Block },
            {"object1300", ObjectType.Block },
            {"object1012", ObjectType.Block },
            {"object1305", ObjectType.Block },
            {"object1009", ObjectType.Block },
            {"object999", ObjectType.Block },
            {"object1018", ObjectType.Block },
            {"object901", ObjectType.Block },
            {"object892", ObjectType.Block },
            {"object891", ObjectType.Block },
            {"object882", ObjectType.Block },
            {"object1258", ObjectType.Block },
            {"object1278", ObjectType.Block },
            {"object915", ObjectType.Block },
            {"object935", ObjectType.Block },
            {"object937", ObjectType.Block },
            {"object1122", ObjectType.Block },
            {"object1263", ObjectType.Block },
            {"object1142", ObjectType.Block },
            {"object943", ObjectType.Block },
            {"object945", ObjectType.Block },
            {"object926", ObjectType.Block },
            {"object925", ObjectType.Block },
            {"object1146", ObjectType.Block },
            {"object911", ObjectType.Block },
            {"object1273", ObjectType.Block },
            {"object954", ObjectType.Block },
            {"object955", ObjectType.Block },
            {"object1094", ObjectType.Block },
            {"object902", ObjectType.Block },
            {"object958", ObjectType.Block },
            {"object1294", ObjectType.Block },
            {"object1099", ObjectType.Block },
            {"object811", ObjectType.Block },
            {"object1082", ObjectType.Block },
            {"object1209", ObjectType.Block },
            {"object1208", ObjectType.Block },
            {"object1252", ObjectType.Block },
            {"object1253", ObjectType.Block },
            {"object1203", ObjectType.Block },
            {"object1202", ObjectType.Block },
            {"object857", ObjectType.Block },
            {"object821", ObjectType.Block },
            {"object858", ObjectType.Block },
            {"object815", ObjectType.Block },
            {"itemblock1-16", ObjectType.Block },
            {"object1193", ObjectType.Block },
            {"object1192", ObjectType.Block },
            {"object837", ObjectType.Block },
            {"object1186", ObjectType.Block },
            {"object805", ObjectType.Block },
            {"object1185", ObjectType.Block },
            {"object1182", ObjectType.Block },
            {"object1177", ObjectType.Block },
            {"object1176", ObjectType.Block },
            {"object1083", ObjectType.Block },
            {"object1170", ObjectType.Block },
            {"object1272", ObjectType.Block },
            {"object1160", ObjectType.Block },
            {"object801", ObjectType.Block },
            {"object1159", ObjectType.Block },
            {"object795", ObjectType.Block },
            {"object870", ObjectType.Block },
            {"object1295", ObjectType.Block },
            {"object1147", ObjectType.Block },
            {"object1280", ObjectType.Block },
            {"object881", ObjectType.Block },
            {"object1133", ObjectType.Block },
            {"object785", ObjectType.Block },
            {"object784", ObjectType.Block },
            {"object1285", ObjectType.Block },
            {"bossblock", ObjectType.Block },
            {"object1132", ObjectType.Block },
            {"object1123", ObjectType.Block },
            {"object1117", ObjectType.Block },
            {"object1112", ObjectType.Block },
            {"object914", ObjectType.Block },
            {"object1103", ObjectType.Block },
            {"object1102", ObjectType.Block },
            {"object871", ObjectType.Block },
            {"object1214", ObjectType.Block },
            {"object1171", ObjectType.Block },
            {"slipblock", ObjectType.Block },
            {"object1237", ObjectType.Block },
            {"object1217", ObjectType.Block },
            {"object1093", ObjectType.Block },
            {"itemblock1-8", ObjectType.Block },
            {"object1222", ObjectType.Block },
            {"object838", ObjectType.Block },
            {"object959", ObjectType.Block },
            {"object1227", ObjectType.Block },
            {"object1307", ObjectType.Block },
            {"bossblock1", ObjectType.Block },
            {"object827", ObjectType.Block },
            {"demobock", ObjectType.Block },
            {"object1064", ObjectType.Block },
            {"object1312", ObjectType.Block },
            {"object1063", ObjectType.Block },
            {"object828", ObjectType.Block },
            {"object1242", ObjectType.Block },
            {"blockNotVis", ObjectType.Block },
            {"object848", ObjectType.Block },
            {"object847", ObjectType.Block },
            {"object1232", ObjectType.Block },
            {"object867", ObjectType.Block },
            {"object1321", ObjectType.Block },
            {"object973", ObjectType.Block },
            {"object1054", ObjectType.Block },
            {"object1053", ObjectType.Block },
            {"object1048", ObjectType.Block },
            {"object1326", ObjectType.Block },
            {"object1039", ObjectType.Block },
            {"object1328", ObjectType.Block },
            {"object1038", ObjectType.Block },
            {"object986", ObjectType.Block },
            {"object1331", ObjectType.Block },
            {"object987", ObjectType.Block },
            {"object1029", ObjectType.Block },
            {"object1028", ObjectType.Block },
            {"object1335", ObjectType.Block },
            {"object998", ObjectType.Block },
            {"object972", ObjectType.Block },
            {"object1338", ObjectType.Block },
            {"object1019", ObjectType.Block },
            {"object1011", ObjectType.Block },
            {"object1341", ObjectType.Block },

            {"miniblock", ObjectType.MiniBlock},
            {"damageblock", ObjectType.KillerBlock},
            {"object1013", ObjectType.KillerBlock},
            {"object1306", ObjectType.KillerBlock},


            {"apple", ObjectType.Apple},
            {"cherry", ObjectType.Apple},
            {"deliciousfruit", ObjectType.Apple},
            {"boundFruit", ObjectType.Apple},
            {"object938", ObjectType.Apple},
            {"object1279", ObjectType.Apple},
            {"deliciousFruit", ObjectType.Apple},
            {"enemybullet", ObjectType.Apple},
            {"fruit", ObjectType.Apple},
            {"free", ObjectType.Apple},
            {"kakusan", ObjectType.Apple},
            {"jikinerai", ObjectType.Apple},
            {"gravityfluit", ObjectType.Apple},
            {"warp", ObjectType.Warp},
            {"warpstart", ObjectType.Warp},
            {"object971", ObjectType.Warp},
            {"object1174", ObjectType.Warp},
            {"object1008", ObjectType.Warp},
            {"object1004", ObjectType.Warp},
            {"object1010", ObjectType.Warp},
            {"object1005", ObjectType.Warp},
            {"object1014", ObjectType.Warp},
            {"object1015", ObjectType.Warp},
            {"object1016", ObjectType.Warp},
            {"object1342", ObjectType.Warp},
            {"object1340", ObjectType.Warp},
            {"object1017", ObjectType.Warp},
            {"object1006", ObjectType.Warp},
            {"object1339", ObjectType.Warp},
            {"object1337", ObjectType.Warp},
            {"object1336", ObjectType.Warp},
            {"object997", ObjectType.Warp},
            {"object996", ObjectType.Warp},
            {"object1024", ObjectType.Warp},
            {"object1025", ObjectType.Warp},
            {"object1026", ObjectType.Warp},
            {"object1027", ObjectType.Warp},
            {"object1334", ObjectType.Warp},
            {"object1333", ObjectType.Warp},
            {"object995", ObjectType.Warp},
            {"object993", ObjectType.Warp},
            {"object1332", ObjectType.Warp},
            {"object1330", ObjectType.Warp},
            {"object1034", ObjectType.Warp},
            {"object1035", ObjectType.Warp},
            {"object1036", ObjectType.Warp},
            {"object1037", ObjectType.Warp},
            {"object1329", ObjectType.Warp},
            {"object1327", ObjectType.Warp},
            {"object985", ObjectType.Warp},
            {"object984", ObjectType.Warp},
            {"object983", ObjectType.Warp},
            {"object982", ObjectType.Warp},
            {"object1044", ObjectType.Warp},
            {"object1045", ObjectType.Warp},
            {"object1046", ObjectType.Warp},
            {"object1047", ObjectType.Warp},
            {"object1325", ObjectType.Warp},
            {"object1051", ObjectType.Warp},
            {"object1052", ObjectType.Warp},
            {"object1324", ObjectType.Warp},
            {"object1323", ObjectType.Warp},
            {"object1322", ObjectType.Warp},
            {"object970", ObjectType.Warp},
            {"object969", ObjectType.Warp},
            {"object1059", ObjectType.Warp},
            {"object1060", ObjectType.Warp},
            {"object1061", ObjectType.Warp},
            {"object1062", ObjectType.Warp},
            {"object968", ObjectType.Warp},
            {"object957", ObjectType.Warp},
            {"object956", ObjectType.Warp},
            {"object953", ObjectType.Warp},
            {"object952", ObjectType.Warp},
            {"object951", ObjectType.Warp},
            {"object950", ObjectType.Warp},
            {"object1074", ObjectType.Warp},
            {"object1075", ObjectType.Warp},
            {"object942", ObjectType.Warp},
            {"object941", ObjectType.Warp},
            {"object940", ObjectType.Warp},
            {"object939", ObjectType.Warp},
            {"object1080", ObjectType.Warp},
            {"object1081", ObjectType.Warp},
            {"object934", ObjectType.Warp},
            {"object933", ObjectType.Warp},
            {"object932", ObjectType.Warp},
            {"object931", ObjectType.Warp},
            {"object923", ObjectType.Warp},
            {"object1089", ObjectType.Warp},
            {"object1090", ObjectType.Warp},
            {"object1091", ObjectType.Warp},
            {"object1092", ObjectType.Warp},
            {"object922", ObjectType.Warp},
            {"object1095", ObjectType.Warp},
            {"object1096", ObjectType.Warp},
            {"object1097", ObjectType.Warp},
            {"object1098", ObjectType.Warp},
            {"object921", ObjectType.Warp},
            {"object1100", ObjectType.Warp},
            {"object1101", ObjectType.Warp},
            {"object1293", ObjectType.Warp},
            {"object920", ObjectType.Warp},
            {"object1292", ObjectType.Warp},
            {"object913", ObjectType.Warp},
            {"object912", ObjectType.Warp},
            {"object1108", ObjectType.Warp},
            {"object1109", ObjectType.Warp},
            {"object1110", ObjectType.Warp},
            {"object1111", ObjectType.Warp},
            {"object1291", ObjectType.Warp},
            {"object910", ObjectType.Warp},
            {"object909", ObjectType.Warp},
            {"object908", ObjectType.Warp},
            {"object907", ObjectType.Warp},
            {"object1290", ObjectType.Warp},
            {"object1118", ObjectType.Warp},
            {"object1119", ObjectType.Warp},
            {"object1120", ObjectType.Warp},
            {"object1121", ObjectType.Warp},
            {"object900", ObjectType.Warp},
            {"object899", ObjectType.Warp},
            {"object898", ObjectType.Warp},
            {"object897", ObjectType.Warp},
            {"object890", ObjectType.Warp},
            {"object1128", ObjectType.Warp},
            {"object1129", ObjectType.Warp},
            {"object1130", ObjectType.Warp},
            {"object1131", ObjectType.Warp},
            {"object786", ObjectType.Warp},
            {"object889", ObjectType.Warp},
            {"object888", ObjectType.Warp},
            {"object887", ObjectType.Warp},
            {"object787", ObjectType.Warp},
            {"object1138", ObjectType.Warp},
            {"object1139", ObjectType.Warp},
            {"object1140", ObjectType.Warp},
            {"object1141", ObjectType.Warp},
            {"object880", ObjectType.Warp},
            {"object1143", ObjectType.Warp},
            {"object1145", ObjectType.Warp},
            {"object879", ObjectType.Warp},
            {"object788", ObjectType.Warp},
            {"object878", ObjectType.Warp},
            {"object877", ObjectType.Warp},
            {"object793", ObjectType.Warp},
            {"object794", ObjectType.Warp},
            {"object869", ObjectType.Warp},
            {"object1154", ObjectType.Warp},
            {"object1155", ObjectType.Warp},
            {"object1157", ObjectType.Warp},
            {"object1158", ObjectType.Warp},
            {"object796", ObjectType.Warp},
            {"object802", ObjectType.Warp},
            {"object1161", ObjectType.Warp},
            {"object868", ObjectType.Warp},
            {"object864", ObjectType.Warp},
            {"object866", ObjectType.Warp},
            {"object865", ObjectType.Warp},
            {"object1166", ObjectType.Warp},
            {"object1167", ObjectType.Warp},
            {"object1168", ObjectType.Warp},
            {"object1169", ObjectType.Warp},
            {"object1271", ObjectType.Warp},
            {"object1270", ObjectType.Warp},
            {"object1172", ObjectType.Warp},
            {"object1173", ObjectType.Warp},
            {"object1007", ObjectType.Warp},
            {"object1175", ObjectType.Warp},
            {"object1269", ObjectType.Warp},
            {"object1268", ObjectType.Warp},
            {"object1178", ObjectType.Warp},
            {"object1179", ObjectType.Warp},
            {"object1180", ObjectType.Warp},
            {"object1181", ObjectType.Warp},
            {"object803", ObjectType.Warp},
            {"object1183", ObjectType.Warp},
            {"object1184", ObjectType.Warp},
            {"object804", ObjectType.Warp},
            {"object810", ObjectType.Warp},
            {"object1187", ObjectType.Warp},
            {"object1188", ObjectType.Warp},
            {"object1189", ObjectType.Warp},
            {"object1190", ObjectType.Warp},
            {"object812", ObjectType.Warp},
            {"object813", ObjectType.Warp},
            {"object1194", ObjectType.Warp},
            {"object1195", ObjectType.Warp},
            {"object814", ObjectType.Warp},
            {"object863", ObjectType.Warp},
            {"object820", ObjectType.Warp},
            {"object822", ObjectType.Warp},
            {"object1200", ObjectType.Warp},
            {"object1201", ObjectType.Warp},
            {"object823", ObjectType.Warp},
            {"object824", ObjectType.Warp},
            {"object1204", ObjectType.Warp},
            {"object1205", ObjectType.Warp},
            {"object1206", ObjectType.Warp},
            {"object1207", ObjectType.Warp},
            {"object1251", ObjectType.Warp},
            {"object1250", ObjectType.Warp},
            {"object1210", ObjectType.Warp},
            {"object1211", ObjectType.Warp},
            {"object1212", ObjectType.Warp},
            {"object1213", ObjectType.Warp},
            {"object1248", ObjectType.Warp},
            {"object1215", ObjectType.Warp},
            {"object1216", ObjectType.Warp},
            {"object1247", ObjectType.Warp},
            {"object825", ObjectType.Warp},
            {"object856", ObjectType.Warp},
            {"object855", ObjectType.Warp},
            {"object854", ObjectType.Warp},
            {"object853", ObjectType.Warp},
            {"object826", ObjectType.Warp},
            {"object833", ObjectType.Warp},
            {"object834", ObjectType.Warp},
            {"object846", ObjectType.Warp},
            {"object845", ObjectType.Warp},
            {"object835", ObjectType.Warp},
            {"object844", ObjectType.Warp},
            {"object843", ObjectType.Warp},
            {"object836", ObjectType.Warp},

            {"playerstart", ObjectType.PlayerStart},
            {"objwater", ObjectType.Water1}, // yuuutu
            {"objwater1", ObjectType.Water1}, // renex
            {"objwater2", ObjectType.Water2}, // renex
            {"objwater3", ObjectType.Water3}, // renex
            {"spikedown", ObjectType.SpikeDown},
            {"object1022", ObjectType.SpikeDown},
            {"object1310", ObjectType.SpikeDown},
            {"object861", ObjectType.SpikeDown},
            {"object818", ObjectType.SpikeDown},
            {"object918", ObjectType.SpikeDown},
            {"object791", ObjectType.SpikeDown},
            {"object1276", ObjectType.SpikeDown},
            {"object799", ObjectType.SpikeDown},
            {"object1087", ObjectType.SpikeDown},
            {"object1266", ObjectType.SpikeDown},
            {"object808", ObjectType.SpikeDown},
            {"object991", ObjectType.SpikeDown},
            {"object1126", ObjectType.SpikeDown},
            {"object929", ObjectType.SpikeDown},
            {"object1106", ObjectType.SpikeDown},
            {"object1136", ObjectType.SpikeDown},
            {"object1032", ObjectType.SpikeDown},
            {"object1256", ObjectType.SpikeDown},
            {"object1042", ObjectType.SpikeDown},
            {"object779", ObjectType.SpikeDown},
            {"object1245", ObjectType.SpikeDown},
            {"object1298", ObjectType.SpikeDown},
            {"spikeDown", ObjectType.SpikeDown},
            {"object976", ObjectType.SpikeDown},
            {"object831", ObjectType.SpikeDown},
            {"object1240", ObjectType.SpikeDown},
            {"object1235", ObjectType.SpikeDown},
            {"object948", ObjectType.SpikeDown},
            {"object841", ObjectType.SpikeDown},
            {"object905", ObjectType.SpikeDown},
            {"object1152", ObjectType.SpikeDown},
            {"object1164", ObjectType.SpikeDown},
            {"object1057", ObjectType.SpikeDown},
            {"object1283", ObjectType.SpikeDown},
            {"object1067", ObjectType.SpikeDown},
            {"object1115", ObjectType.SpikeDown},
            {"object966", ObjectType.SpikeDown},
            {"object1230", ObjectType.SpikeDown},
            {"object851", ObjectType.SpikeDown},
            {"object961", ObjectType.SpikeDown},
            {"object1225", ObjectType.SpikeDown},
            {"object1315", ObjectType.SpikeDown},
            {"object1261", ObjectType.SpikeDown},
            {"object895", ObjectType.SpikeDown},
            {"object885", ObjectType.SpikeDown},
            {"object874", ObjectType.SpikeDown},
            {"object1002", ObjectType.SpikeDown},
            {"object1303", ObjectType.SpikeDown},

            {"spikeleft", ObjectType.SpikeLeft},
            {"object1311", ObjectType.SpikeLeft},
            {"object1023", ObjectType.SpikeLeft},
            {"object1267", ObjectType.SpikeLeft},
            {"object1088", ObjectType.SpikeLeft},
            {"object1241", ObjectType.SpikeLeft},
            {"object1246", ObjectType.SpikeLeft},
            {"object1137", ObjectType.SpikeLeft},
            {"object1226", ObjectType.SpikeLeft},
            {"object1257", ObjectType.SpikeLeft},
            {"object1127", ObjectType.SpikeLeft},
            {"object819", ObjectType.SpikeLeft},
            {"object1153", ObjectType.SpikeLeft},
            {"object1165", ObjectType.SpikeLeft},
            {"object809", ObjectType.SpikeLeft},
            {"object1231", ObjectType.SpikeLeft},
            {"object1116", ObjectType.SpikeLeft},
            {"object1284", ObjectType.SpikeLeft},
            {"object906", ObjectType.SpikeLeft},
            {"object1107", ObjectType.SpikeLeft},
            {"object919", ObjectType.SpikeLeft},
            {"object852", ObjectType.SpikeLeft},
            {"object930", ObjectType.SpikeLeft},
            {"object800", ObjectType.SpikeLeft},
            {"object1277", ObjectType.SpikeLeft},
            {"object792", ObjectType.SpikeLeft},
            {"object832", ObjectType.SpikeLeft},
            {"object949", ObjectType.SpikeLeft},
            {"object862", ObjectType.SpikeLeft},
            {"object1068", ObjectType.SpikeLeft},
            {"object1316", ObjectType.SpikeLeft},
            {"object963", ObjectType.SpikeLeft},
            {"object967", ObjectType.SpikeLeft},
            {"object1058", ObjectType.SpikeLeft},
            {"object1236", ObjectType.SpikeLeft},
            {"object842", ObjectType.SpikeLeft},
            {"spikeLeft", ObjectType.SpikeLeft},
            {"object1043", ObjectType.SpikeLeft},
            {"object1299", ObjectType.SpikeLeft},
            {"object977", ObjectType.SpikeLeft},
            {"object1033", ObjectType.SpikeLeft},
            {"object992", ObjectType.SpikeLeft},
            {"object875", ObjectType.SpikeLeft},
            {"object1003", ObjectType.SpikeLeft},
            {"object1304", ObjectType.SpikeLeft},
            {"object886", ObjectType.SpikeLeft},
            {"object896", ObjectType.SpikeLeft},
            {"object1262", ObjectType.SpikeLeft},

            {"spikeright", ObjectType.SpikeRight},
            {"object1309", ObjectType.SpikeRight},
            {"object1021", ObjectType.SpikeRight},
            {"object1297", ObjectType.SpikeRight},
            {"object1229", ObjectType.SpikeRight},
            {"object1031", ObjectType.SpikeRight},
            {"object990", ObjectType.SpikeRight},
            {"object1066", ObjectType.SpikeRight},
            {"object807", ObjectType.SpikeRight},
            {"object860", ObjectType.SpikeRight},
            {"object1314", ObjectType.SpikeRight},
            {"object1163", ObjectType.SpikeRight},
            {"object1265", ObjectType.SpikeRight},
            {"object975", ObjectType.SpikeRight},
            {"object1234", ObjectType.SpikeRight},
            {"object1151", ObjectType.SpikeRight},
            {"object1105", ObjectType.SpikeRight},
            {"object1056", ObjectType.SpikeRight},
            {"object830", ObjectType.SpikeRight},
            {"object840", ObjectType.SpikeRight},
            {"object947", ObjectType.SpikeRight},
            {"object1239", ObjectType.SpikeRight},
            {"object1114", ObjectType.SpikeRight},
            {"spikeRight", ObjectType.SpikeRight},
            {"object798", ObjectType.SpikeRight},
            {"object1086", ObjectType.SpikeRight},
            {"object1255", ObjectType.SpikeRight},
            {"object962", ObjectType.SpikeRight},
            {"object1244", ObjectType.SpikeRight},
            {"object928", ObjectType.SpikeRight},
            {"object1135", ObjectType.SpikeRight},
            {"object1275", ObjectType.SpikeRight},
            {"object850", ObjectType.SpikeRight},
            {"object1282", ObjectType.SpikeRight},
            {"object904", ObjectType.SpikeRight},
            {"object917", ObjectType.SpikeRight},
            {"object1224", ObjectType.SpikeRight},
            {"object817", ObjectType.SpikeRight},
            {"object1125", ObjectType.SpikeRight},
            {"object790", ObjectType.SpikeRight},
            {"object965", ObjectType.SpikeRight},
            {"object1041", ObjectType.SpikeRight},
            {"object884", ObjectType.SpikeRight},
            {"object894", ObjectType.SpikeRight},
            {"object1260", ObjectType.SpikeRight},
            {"object873", ObjectType.SpikeRight},
            {"object1001", ObjectType.SpikeRight},
            {"object1302", ObjectType.SpikeRight},

            {"spikeup", ObjectType.SpikeUp},
            {"object1308", ObjectType.SpikeUp},
            {"object1020", ObjectType.SpikeUp},
            {"object806", ObjectType.SpikeUp},
            {"object964", ObjectType.SpikeUp},
            {"object1113", ObjectType.SpikeUp},
            {"object903", ObjectType.SpikeUp},
            {"object789", ObjectType.SpikeUp},
            {"object1124", ObjectType.SpikeUp},
            {"object916", ObjectType.SpikeUp},
            {"object1296", ObjectType.SpikeUp},
            {"object927", ObjectType.SpikeUp},
            {"object1134", ObjectType.SpikeUp},
            {"object1274", ObjectType.SpikeUp},
            {"object797", ObjectType.SpikeUp},
            {"object1085", ObjectType.SpikeUp},
            {"object946", ObjectType.SpikeUp},
            {"spikemiller", ObjectType.SpikeUp},
            {"object1150", ObjectType.SpikeUp},
            {"object1281", ObjectType.SpikeUp},
            {"object1030", ObjectType.SpikeUp},
            {"object1162", ObjectType.SpikeUp},
            {"object1264", ObjectType.SpikeUp},
            {"object1313", ObjectType.SpikeUp},
            {"object859", ObjectType.SpikeUp},
            {"object1065", ObjectType.SpikeUp},
            {"object989", ObjectType.SpikeUp},
            {"object1223", ObjectType.SpikeUp},
            {"object960", ObjectType.SpikeUp},
            {"spikeUp", ObjectType.SpikeUp},
            {"object849", ObjectType.SpikeUp},
            {"object1228", ObjectType.SpikeUp},
            {"object1040", ObjectType.SpikeUp},
            {"object816", ObjectType.SpikeUp},
            {"object1104", ObjectType.SpikeUp},
            {"object1233", ObjectType.SpikeUp},
            {"object839", ObjectType.SpikeUp},
            {"object1055", ObjectType.SpikeUp},
            {"object1238", ObjectType.SpikeUp},
            {"object974", ObjectType.SpikeUp},
            {"object1254", ObjectType.SpikeUp},
            {"object829", ObjectType.SpikeUp},
            {"object1243", ObjectType.SpikeUp},
            {"object872", ObjectType.SpikeUp},
            {"object1000", ObjectType.SpikeUp},
            {"object1301", ObjectType.SpikeUp},
            {"object1259", ObjectType.SpikeUp},
            {"object893", ObjectType.SpikeUp},
            {"object883", ObjectType.SpikeUp},


            {"minispikedown", ObjectType.MiniSpikeDown},
            {"object1288", ObjectType.MiniSpikeDown},
            {"object979", ObjectType.MiniSpikeDown},
 
            {"minispikeleft", ObjectType.MiniSpikeLeft},
            {"object1289", ObjectType.MiniSpikeLeft},
            {"object981", ObjectType.MiniSpikeLeft},
          
            {"minispikeright", ObjectType.MiniSpikeRight},
            {"object1287", ObjectType.MiniSpikeRight},
            {"object980", ObjectType.MiniSpikeRight},
 
            {"minispikeup", ObjectType.MiniSpikeUp},
            {"object978", ObjectType.MiniSpikeUp},
            {"object1286", ObjectType.MiniSpikeUp},
     
            {"playerkiller", ObjectType.SpikeDown},
            {"walljumpl", ObjectType.VineLeft},
            {"walljumpr", ObjectType.VineRight},
            {"platform", ObjectType.Platform}, // yuuutu platform hitbox is a lot smaller than the regular one, good luck distinguishing here
            {"movingplatform", ObjectType.Platform}, // like this one should have the regular hitbox but not the other one since its just supposed to be an object parent
            {"object988", ObjectType.Platform},

            {"catharsiswater", ObjectType.CatharsisWater},
            {"grav_up", ObjectType.GravityArrowUp },
            {"grav_down", ObjectType.GravityArrowDown },
            {"obj_ue", ObjectType.GravityArrowUp },
            {"obj_sita", ObjectType.GravityArrowDown },
            {"object1073", ObjectType.JumboBlock },
            {"object1199", ObjectType.JumboSpikeLeft },
            {"object1320", ObjectType.JumboSpikeLeft },
            {"object1072", ObjectType.JumboSpikeLeft },
            {"object1079", ObjectType.JumboSpikeLeft },
            {"object1069", ObjectType.JumboSpikeUp },
            {"object1196", ObjectType.JumboSpikeUp },
            {"object1317", ObjectType.JumboSpikeUp },
            {"object1076", ObjectType.JumboSpikeUp },
            {"object1070", ObjectType.JumboSpikeRight },
            {"object1318", ObjectType.JumboSpikeRight },
            {"object1197", ObjectType.JumboSpikeRight },
            {"object1077", ObjectType.JumboSpikeRight },
            {"object1198", ObjectType.JumboSpikeDown },
            {"object1071", ObjectType.JumboSpikeDown },
            {"object1319", ObjectType.JumboSpikeDown },
            {"object1078", ObjectType.JumboSpikeDown },


        };
    }
}

